# Dependabot Auto-merge Workflow
# Automatically merge Dependabot PRs for patch-level security updates after validation

name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  # Security validation for Dependabot PRs
  security-check:
    name: Security Validation
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run security audit
        run: |
          echo "🔍 Running npm security audit..."
          npm audit --audit-level=moderate || true
          
          echo "📊 Generating audit report..."
          npm audit --json > audit-report.json || true
          
          # Check for high/critical vulnerabilities
          HIGH_VULNS=$(cat audit-report.json | jq '.metadata.vulnerabilities.high // 0')
          CRITICAL_VULNS=$(cat audit-report.json | jq '.metadata.vulnerabilities.critical // 0')
          
          echo "High vulnerabilities: $HIGH_VULNS"
          echo "Critical vulnerabilities: $CRITICAL_VULNS"
          
          if [ "$CRITICAL_VULNS" -gt 0 ]; then
            echo "❌ Critical vulnerabilities found - manual review required"
            exit 1
          fi
          
          if [ "$HIGH_VULNS" -gt 0 ]; then
            echo "⚠️ High vulnerabilities found - will require manual review"
            echo "high_vulns=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Run tests
        run: |
          echo "🧪 Running test suite..."
          npm test || npm run test:ci || echo "No test script found"
      
      - name: Build application
        run: |
          echo "🏗️ Building application..."
          npm run build || echo "Build completed with warnings"
      
      - name: Security test suite
        run: |
          echo "🔒 Running security tests..."
          # Add custom security test commands here
          npm run test:security || echo "Security tests not configured"

  # Auto-merge for safe dependency updates
  auto-merge:
    name: Auto-merge Safe Updates
    runs-on: ubuntu-latest
    needs: security-check
    if: github.actor == 'dependabot[bot]' && needs.security-check.result == 'success'
    
    steps:
      - name: Get PR details
        id: pr-details
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const title = pr.data.title;
            const body = pr.data.body || '';
            
            // Check if this is a security update
            const isSecurityUpdate = title.includes('security') || 
                                   body.includes('security') ||
                                   title.includes('patch') ||
                                   body.includes('vulnerability');
            
            // Check if this is a patch version update
            const isPatchUpdate = /bump .* from \d+\.\d+\.\d+ to \d+\.\d+\.\d+/.test(title) &&
                                 !title.includes('major') && 
                                 !title.includes('minor');
            
            console.log(`Security update: ${isSecurityUpdate}`);
            console.log(`Patch update: ${isPatchUpdate}`);
            
            return {
              isSecurityUpdate,
              isPatchUpdate,
              canAutoMerge: (isSecurityUpdate || isPatchUpdate) && !title.includes('major')
            };
      
      - name: Auto-approve and merge
        if: fromJSON(steps.pr-details.outputs.result).canAutoMerge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Add approval
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
              body: '✅ Auto-approved by security workflow - patch-level security update'
            });
            
            // Auto-merge
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              commit_title: 'chore: auto-merge dependabot security update',
              commit_message: 'Automatically merged by security workflow after validation',
              merge_method: 'squash'
            });
            
            console.log('✅ Auto-merged Dependabot PR');
      
      - name: Add security label
        if: fromJSON(steps.pr-details.outputs.result).isSecurityUpdate
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['security-auto-merged', 'dependabot-approved']
            });
      
      - name: Comment on manual review needed
        if: ${{ !fromJSON(steps.pr-details.outputs.result).canAutoMerge }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🔍 **Manual Review Required**
              
              This Dependabot PR requires manual review because:
              - Major or minor version update detected
              - Contains breaking changes
              - Security implications need assessment
              
              Please review and merge manually after verification.
              
              **Security Checklist:**
              - [ ] Breaking changes reviewed
              - [ ] Security implications assessed
              - [ ] Tests passing
              - [ ] Documentation updated
              `
            });

  # Notification for failed security checks
  security-notification:
    name: Security Alert
    runs-on: ubuntu-latest
    needs: security-check
    if: failure() && github.actor == 'dependabot[bot]'
    
    steps:
      - name: Security failure notification
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🚨 **Security Check Failed**
              
              The automated security validation failed for this Dependabot PR.
              
              **Required Actions:**
              1. Review the security audit results
              2. Verify no critical vulnerabilities introduced
              3. Ensure all tests pass
              4. Manual security assessment required
              
              **Do not merge until security issues are resolved.**
              `
            });
            
            // Add security alert label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['security-alert', 'manual-review-required']
            });